config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'events#index'
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
  end

  def create
    @event = Event.new(event_params)
    @event.save
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :date, :location, :expenses)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<% @events.each do |event| %>
  <p><%= event.title %></p>
  <p><%= event.date %></p>
  <p><%= event.location %></p>
  <p><%= event.expenses %></p>
<% end %>

app/views/events/new.html.erb
<div class="container">
  <div class="path-container">
    <%= link_to root_path do %>
      <p> Back to Events</p>
    <% end %>
  </div>
  <div class="card-container">
    <%= form_with model: @event do |f| %>
          <%= f.text_field :title, placeholder:"What would you like to do?" %>
          <%= f.text_field :location, placeholder:"Add location" %>
          <%= f.date_field :date %>
          <div class="expense-field">
            <p>Cover expenses?</p><%= f.check_box :expenses %>
          </div>
          <%= f.submit%>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<%= @event.name %>
<%= @event.date %>
<%= @event.location %>
<%= @event.expense %>

app/views/layouts/_navbar.html.erb
<div class="navbar-container">
    <div class="logo-container">
      <%= link_to root_path do %>
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="91" height="91" viewBox="0 0 91 91">
          <defs>
            <radialGradient id="radial-gradient" cx="0.5" cy="0.5" r="0.64" gradientTransform="matrix(-0.995, 0.097, -0.097, -0.995, 1.046, 0.949)" gradientUnits="objectBoundingBox">
              <stop offset="0" stop-color="#ed5f70"/>
              <stop offset="1" stop-color="#f05a43"/>
            </radialGradient>
          </defs>
          <g id="Group_1883" data-name="Group 1883" transform="translate(45 82.62)">
            <circle id="Ellipse_35" data-name="Ellipse 35" cx="45.5" cy="45.5" r="45.5" transform="translate(-45 -82.62)" fill="url(#radial-gradient)"/>
            <g id="Icon_Premium" data-name="Icon Premium" transform="translate(-21.768 -59.768)">
              <path id="Path_103" data-name="Path 103" d="M32.325,19.152A26.508,26.508,0,0,0,24.614,2a27.4,27.4,0,0,0-7.98,17.152,31.172,31.172,0,0,1,7.845,5.912,32.276,32.276,0,0,1,7.845-5.912ZM17.713,25.109c-.315-.225-.674-.427-1.012-.652C17.039,24.7,17.4,24.884,17.713,25.109Zm14.432-.562c-.292.2-.607.36-.9.584C31.538,24.907,31.853,24.749,32.145,24.547ZM24.48,32.235A26.853,26.853,0,0,0,2,19.984,27.366,27.366,0,0,0,20.051,45.813a24.163,24.163,0,0,0,4.428,1.146,29.09,29.09,0,0,0,4.428-1.146A27.366,27.366,0,0,0,46.959,19.984,26.853,26.853,0,0,0,24.48,32.235Z" transform="translate(-2 -2)" fill="#20232a"/>
            </g>
          </g>
        </svg>
        <%# <img src="../../assets/images/bloomlogo.jpg" alt=""> %>
        <h1>BLOOM</h1>
      <% end %>
    </div>
    <div class = "navbar-right">
      <div class="box">
        <form name="search">
            <input type="text" class="input" name="txt" onmouseout="this.value = ''; this.blur();">
        </form>
        <i class="fas fa-search"></i>
      </div>
      <div class="button">
        <%# <%= link_to user_path %>
        <i class="fas fa-hoouse"></i>
        <%# <% end %>
      </div>
      <div class="button">
        <%= link_to new_event_path do %>
        <i class="fas fa-plus"></i>
        <% end %>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventHosting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:25,100,200,300,400,600" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>